### ISSUE TITLE
fix: drop defaultLanguage

### ISSUE THREAD

**Issue by Eomm** [mateonunez/fastify-lyra#150]
https://github.com/mateonunez/fastify-orama/blob/3b616916f7192b1e740cc67fb6c740d4d297e59c/index.js#L40C7-L40C22

I can't find any `defaultLanguage` prop to provide to orama:

<img width="595" alt="image" src="https://github.com/mateonunez/fastify-orama/assets/11404065/dcd27a7b-a38d-4d04-bb8e-bb3e1b4fea5a">

I think we should improve the stemming option instead:

https://docs.oramasearch.com/text-analysis/stemming

**Comment by mateonunez** [comment]
Nice catch! I think this is legacy code from old Lyra's integration. 

This would be a nice **good first issue**, what do you think?
