### ISSUE TITLE
fix: remove dep pin

### ISSUE THREAD

**Issue by Eomm** [mateonunez/fastify-lyra#152]
https://github.com/mateonunez/fastify-orama/blob/3b616916f7192b1e740cc67fb6c740d4d297e59c/package.json#L38-L39

Orama follows the semver standard, so why do we pin the dependencies?

**Comment by mateonunez** [comment]
Nice catch, @Eomm! I think the pin is an error in the vscode plugin to bump the version's package.

Do you want to send a PR to fix this? 🙏
