### ISSUE TITLE
feat: improve persistence usability

### ISSUE THREAD

**Issue by Eomm** [mateonunez/fastify-lyra#153]
https://github.com/mateonunez/fastify-orama/blob/3b616916f7192b1e740cc67fb6c740d4d297e59c/index.js#L28-L30

The first run of the application, the file will never exist until the dev calls `save()`

If we keep this persistence utility (totally pro to this) we should improve the DX

**Comment by mateonunez** [comment]
This enhancement will improve a lot the DX and the plugin's behavior! 🚀 

What do you suggest?
